name = "Chris Laffra"

[files]
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/jquery.py" = "ltk/jquery.py"
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/widgets.py" = "ltk/widgets.py"
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/pubsub.py" = "ltk/pubsub.py"
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/__init__.py" = "ltk/__init__.py"
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/logger.py" = "ltk/logger.py"
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/ltk.js" = "ltk/ltk.js"
"https://raw.githubusercontent.com/laffra/ltk/main/ltk/ltk.css" = "ltk/ltk.css"
